name: Lint github workflows

on:
  push:
    paths:
      - ".github/**"

jobs:
  actionlint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: lint github workflows and actions
        run: actionlint
